import org.gradle.kotlin.dsl.apply

/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    val kotlinVersion: String by settings

    plugins {
        kotlin("jvm") version kotlinVersion apply false
        kotlin("plugin.serialization") version kotlinVersion apply false
    }
}

include("database-sync")
include("sample-module")
include("presence-monitor")
include("poma-manager")
if (System.getenv().containsKey("SKAARD_DEVELOP")) include("app")