/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    val kotlinVersion: String by settings

    plugins {
        kotlin("jvm") version kotlinVersion apply false
        kotlin("plugin.serialization") version kotlinVersion apply false
        id("io.kotest") version "0.4.11" apply false
    }
}

include("database-sync")
include("sample-module")
include("presence-monitor")
include("app")