[kord-db-sync]
[kord-db-sync.r2dbc]
url = 'r2dbc:postgresql://localhost:5432/postgres'
user = 'postgres'
password = 'postgres'

[kord-db-sync.jdbc]
url = 'jdbc:postgresql://localhost:5432/postgres'
user = 'postgres'
password = 'postgres'